// Definisi 35 Achievement Badges Kimia untuk Sistem Gamifikasi Siswa OSN Kimia

export type AchievementCategory = 'habit' | 'skill' | 'lab' | 'katex' | 'quirk';
export type AchievementRarity = 'common' | 'rare' | 'epic' | 'mythic' | 'secret';

export interface AchievementDefinition {
  id: string;
  title: string;
  description: string;
  category: AchievementCategory;
  categoryName: string;
  rarity: AchievementRarity;
  icon: string;
  emoji: string;
  targetValue: number;
  unit: string;
  xpReward: number;
  isSecret?: boolean;
  secretHint?: string;
  badgeStyle: {
    bg: string;
    border: string;
    text: string;
    glow: string;
  };
}

export const ACHIEVEMENT_CATEGORIES: Record<
  AchievementCategory,
  { name: string; description: string; emoji: string }
> = {
  habit: {
    name: 'Disiplin & Waktu',
    description: 'Konsistensi dan ketahanan belajar siswa secara berkesinambungan',
    emoji: '⏱️',
  },
  skill: {
    name: 'Ketelitian & Uji Soal',
    description: 'Pencapaian performa, akurasi penalaran, dan keberhasilan soal olimpiade',
    emoji: '🎯',
  },
  lab: {
    name: 'Alat Lab Digital',
    description: 'Pemanfaatan maksimal kalkulator Mr, tabel periodik, dan lembar kerja',
    emoji: '🧪',
  },
  katex: {
    name: 'Notasi Ilmiah & KaTeX',
    description: 'Kecakapan merangkai rumus, panah reaksi, pecahan, dan ionik',
    emoji: '✍️',
  },
  quirk: {
    name: 'Misi Unik & Rahasia',
    description: 'Easter eggs, eksplorasi iseng, dan momen seru kimia yang tak terduga',
    emoji: '✨',
  },
};

export const RARITY_STYLES: Record<
  AchievementRarity,
  { label: string; badge: string; color: string; border: string; glow: string }
> = {
  common: {
    label: 'Common',
    badge: 'bg-[#B0C4DE]/20 text-[#4A5867] border-[#B0C4DE]/60',
    color: '#708090',
    border: 'border-[#B0C4DE]',
    glow: 'shadow-2xs',
  },
  rare: {
    label: 'Rare',
    badge: 'bg-[#F0F8FF] text-[#2D3748] border-[#B0C4DE]',
    color: '#2D3748',
    border: 'border-[#B0C4DE]',
    glow: 'shadow-xs',
  },
  epic: {
    label: 'Epic',
    badge: 'bg-[#FFF2CC] text-[#806000] border-[#FFE599]',
    color: '#D4A359',
    border: 'border-[#D4A359]',
    glow: 'shadow-md shadow-[#D4A359]/20 ring-1 ring-[#D4A359]/40',
  },
  mythic: {
    label: 'Mythic',
    badge: 'bg-[#E2F0D9] text-[#2E6930] border-[#C5E0B4]',
    color: '#2E6930',
    border: 'border-[#2E6930]',
    glow: 'shadow-lg shadow-[#2E6930]/25 ring-2 ring-[#2E6930]/40',
  },
  secret: {
    label: 'Rahasia',
    badge: 'bg-gradient-to-r from-purple-100 to-amber-100 text-purple-900 border-purple-300',
    color: '#7C3AED',
    border: 'border-purple-300',
    glow: 'shadow-md shadow-purple-500/20 ring-1 ring-purple-400',
  },
};

export const ACHIEVEMENTS: AchievementDefinition[] = [
  // ==================== KATEGORI 1: DISIPLIN & WAKTU (7 BADGES) ====================
  {
    id: 'bunsen_warmup',
    title: 'Pemanasan Bunsen',
    description: 'Membuka lembar kerja atau materi teori dan aktif belajar selama minimal 5 menit tanpa jeda.',
    category: 'habit',
    categoryName: 'Disiplin & Waktu',
    rarity: 'common',
    icon: 'Flame',
    emoji: '🔥',
    targetValue: 5,
    unit: 'menit',
    xpReward: 30,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'supercritical_focus',
    title: 'Fase Superkritis',
    description: 'Menjaga fokus belajar di lembar kerja atau membaca materi selama lebih dari 30 menit dalam satu sesi.',
    category: 'habit',
    categoryName: 'Disiplin & Waktu',
    rarity: 'rare',
    icon: 'Hourglass',
    emoji: '⏳',
    targetValue: 30,
    unit: 'menit',
    xpReward: 100,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'streak_3',
    title: 'Reaksi Berantai (Level 1)',
    description: 'Login dan menyelesaikan minimal satu aktivitas belajar selama 3 hari berturut-turut.',
    category: 'habit',
    categoryName: 'Disiplin & Waktu',
    rarity: 'common',
    icon: 'Zap',
    emoji: '⚡',
    targetValue: 3,
    unit: 'hari',
    xpReward: 75,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'streak_7',
    title: 'Kesetimbangan Dinamis',
    description: 'Menjaga streak belajar selama 7 hari berturut-turut tanpa pernah terputus.',
    category: 'habit',
    categoryName: 'Disiplin & Waktu',
    rarity: 'epic',
    icon: 'Repeat',
    emoji: '🔄',
    targetValue: 7,
    unit: 'hari',
    xpReward: 250,
    badgeStyle: {
      bg: 'bg-[#FFF2CC]',
      border: 'border-[#D4A359]',
      text: 'text-[#806000]',
      glow: 'shadow-md shadow-[#D4A359]/20',
    },
  },
  {
    id: 'streak_30',
    title: 'Isotop Abadi',
    description: 'Mempertahankan konsistensi belajar harian selama 30 hari penuh berturut-turut.',
    category: 'habit',
    categoryName: 'Disiplin & Waktu',
    rarity: 'mythic',
    icon: 'Infinity',
    emoji: '💎',
    targetValue: 30,
    unit: 'hari',
    xpReward: 1000,
    badgeStyle: {
      bg: 'bg-[#E2F0D9]',
      border: 'border-[#2E6930]',
      text: 'text-[#2E6930]',
      glow: 'shadow-lg shadow-[#2E6930]/30',
    },
  },
  {
    id: 'night_owl',
    title: 'Burung Hantu Lab',
    description: 'Menyelesaikan evaluasi soal di antara pukul 23:00 malam hingga 04:00 dini hari.',
    category: 'habit',
    categoryName: 'Disiplin & Waktu',
    rarity: 'rare',
    icon: 'Moon',
    emoji: '🦉',
    targetValue: 1,
    unit: 'kali',
    xpReward: 80,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'early_bird',
    title: 'Fotokimia Pagi Buta',
    description: 'Membuka aplikasi dan mengerjakan latihan soal sebelum pukul 06:00 pagi.',
    category: 'habit',
    categoryName: 'Disiplin & Waktu',
    rarity: 'rare',
    icon: 'Sunrise',
    emoji: '🌅',
    targetValue: 1,
    unit: 'kali',
    xpReward: 80,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'purrfect_streak_14',
    title: 'Pelepasan Kalor Stabil (14 Hari)',
    description: 'Mempertahankan streak belajar kimia selama 2 pekan (14 hari berturut-turut) tanpa jeda.',
    category: 'habit',
    categoryName: 'Disiplin & Waktu',
    rarity: 'epic',
    icon: 'Flame',
    emoji: '🐾',
    targetValue: 14,
    unit: 'hari',
    xpReward: 500,
    badgeStyle: {
      bg: 'bg-[#FFF2CC]',
      border: 'border-[#D4A359]',
      text: 'text-[#806000]',
      glow: 'shadow-md shadow-[#D4A359]/20',
    },
  },
  {
    id: 'weekend_catalyst',
    title: 'Katalis Akhir Pekan',
    description: 'Menyelesaikan minimal 1 latihan soal atau membaca modul pada hari Sabtu atau Minggu.',
    category: 'habit',
    categoryName: 'Disiplin & Waktu',
    rarity: 'common',
    icon: 'Calendar',
    emoji: '📅',
    targetValue: 1,
    unit: 'sesi',
    xpReward: 40,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'lunchtime_titration',
    title: 'Titrasi Jam Istirahat',
    description: 'Belajar dan submit latihan soal di sela-sela jam istirahat siang (11:30 - 13:30).',
    category: 'habit',
    categoryName: 'Disiplin & Waktu',
    rarity: 'common',
    icon: 'Coffee',
    emoji: '🥪',
    targetValue: 1,
    unit: 'kali',
    xpReward: 40,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'marathon_session_60',
    title: 'Konsentrasi Kucing Peneliti (60 Menit)',
    description: 'Satu sesi belajar mendalam di lembar kerja atau materi teori tanpa henti selama 60 menit.',
    category: 'habit',
    categoryName: 'Disiplin & Waktu',
    rarity: 'epic',
    icon: 'Timer',
    emoji: '🧘',
    targetValue: 60,
    unit: 'menit',
    xpReward: 250,
    badgeStyle: {
      bg: 'bg-[#FFF2CC]',
      border: 'border-[#D4A359]',
      text: 'text-[#806000]',
      glow: 'shadow-md shadow-[#D4A359]/20',
    },
  },

  // ==================== KATEGORI 2: KETELITIAN & PERFORMA UJI SOAL (12 BADGES) ====================
  {
    id: 'first_hundred',
    title: 'Seratus Pertama',
    description: 'Meraih skor sempurna (10/10) untuk pertama kalinya pada soal kimia di lembar kerja.',
    category: 'skill',
    categoryName: 'Ketelitian & Uji Soal',
    rarity: 'common',
    icon: 'Target',
    emoji: '🎯',
    targetValue: 1,
    unit: 'kali',
    xpReward: 50,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'spontaneous_reaction',
    title: 'Reaksi Spontan (ΔG < 0)',
    description: 'Menyelesaikan 1 soal dalam waktu kurang dari 2 menit dan meraih nilai 10/10.',
    category: 'skill',
    categoryName: 'Ketelitian & Uji Soal',
    rarity: 'rare',
    icon: 'Clock',
    emoji: '⚡',
    targetValue: 1,
    unit: 'kali',
    xpReward: 120,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'corrosion_resistant',
    title: 'Tahan Korosi (Pantang Menyerah)',
    description: 'Mengulang pengerjaan soal yang sebelumnya bernilai di bawah 50 hingga berhasil meraih nilai 100.',
    category: 'skill',
    categoryName: 'Ketelitian & Uji Soal',
    rarity: 'rare',
    icon: 'Shield',
    emoji: '🛡️',
    targetValue: 1,
    unit: 'kali',
    xpReward: 100,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'precision_stoichiometry',
    title: 'Stoikiometri Presisi',
    description: 'Menjawab soal tipe perhitungan kuantitatif dengan ketepatan nilai tanpa selisih error.',
    category: 'skill',
    categoryName: 'Ketelitian & Uji Soal',
    rarity: 'common',
    icon: 'Scale',
    emoji: '⚖️',
    targetValue: 1,
    unit: 'kali',
    xpReward: 50,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'great_catalyst',
    title: 'Katalisator Handal',
    description: 'Meraih skor 10/10 secara berturut-turut pada 3 soal berbeda dalam 1 sesi belajar.',
    category: 'skill',
    categoryName: 'Ketelitian & Uji Soal',
    rarity: 'epic',
    icon: 'Rocket',
    emoji: '🚀',
    targetValue: 3,
    unit: 'soal',
    xpReward: 200,
    badgeStyle: {
      bg: 'bg-[#FFF2CC]',
      border: 'border-[#D4A359]',
      text: 'text-[#806000]',
      glow: 'shadow-md shadow-[#D4A359]/20',
    },
  },
  {
    id: 'osn_detective',
    title: 'Detektif OSN',
    description: 'Berhasil menyelesaikan soal bertingkat seleksi OSN (Nasional) atau IChO dengan skor minimal 80.',
    category: 'skill',
    categoryName: 'Ketelitian & Uji Soal',
    rarity: 'epic',
    icon: 'Search',
    emoji: '🏅',
    targetValue: 1,
    unit: 'soal',
    xpReward: 300,
    badgeStyle: {
      bg: 'bg-[#FFF2CC]',
      border: 'border-[#D4A359]',
      text: 'text-[#806000]',
      glow: 'shadow-md shadow-[#D4A359]/20',
    },
  },
  {
    id: 'midas_touch',
    title: 'Sentuhan Midas Alkimia',
    description: 'Mengumpulkan total akumulasi 1.000 XP murni dari pengerjaan soal di lembar kerja siswa.',
    category: 'skill',
    categoryName: 'Ketelitian & Uji Soal',
    rarity: 'epic',
    icon: 'Coins',
    emoji: '💰',
    targetValue: 1000,
    unit: 'XP',
    xpReward: 250,
    badgeStyle: {
      bg: 'bg-[#FFF2CC]',
      border: 'border-[#D4A359]',
      text: 'text-[#806000]',
      glow: 'shadow-md shadow-[#D4A359]/20',
    },
  },
  {
    id: 'bank_grandmaster',
    title: 'Grandmaster Bank Soal',
    description: 'Menyelesaikan total 50 butir soal latihan dari berbagai topik kimia.',
    category: 'skill',
    categoryName: 'Ketelitian & Uji Soal',
    rarity: 'mythic',
    icon: 'Crown',
    emoji: '👑',
    targetValue: 50,
    unit: 'soal',
    xpReward: 800,
    badgeStyle: {
      bg: 'bg-[#E2F0D9]',
      border: 'border-[#2E6930]',
      text: 'text-[#2E6930]',
      glow: 'shadow-lg shadow-[#2E6930]/30',
    },
  },
  {
    id: 'flawless_five',
    title: 'Reaksi Sempurna Beruntun (5 Soal)',
    description: 'Meraih skor sempurna 10/10 pada 5 soal berbeda berturut-turut dalam lembar kerja.',
    category: 'skill',
    categoryName: 'Ketelitian & Uji Soal',
    rarity: 'epic',
    icon: 'Sparkles',
    emoji: '⭐',
    targetValue: 5,
    unit: 'soal',
    xpReward: 350,
    badgeStyle: {
      bg: 'bg-[#FFF2CC]',
      border: 'border-[#D4A359]',
      text: 'text-[#806000]',
      glow: 'shadow-md shadow-[#D4A359]/20',
    },
  },
  {
    id: 'half_century_xp',
    title: 'Reaktor 2.500 XP',
    description: 'Mengumpulkan akumulasi 2.500 XP dari hasil pengerjaan soal dan latihan olimpiade.',
    category: 'skill',
    categoryName: 'Ketelitian & Uji Soal',
    rarity: 'epic',
    icon: 'Zap',
    emoji: '⚡',
    targetValue: 2500,
    unit: 'XP',
    xpReward: 500,
    badgeStyle: {
      bg: 'bg-[#FFF2CC]',
      border: 'border-[#D4A359]',
      text: 'text-[#806000]',
      glow: 'shadow-md shadow-[#D4A359]/20',
    },
  },
  {
    id: 'century_solver',
    title: 'Senturion Kimiawan (100 Soal)',
    description: 'Menyelesaikan total 100 butir soal latihan olimpiade dan SMA dari bank soal.',
    category: 'skill',
    categoryName: 'Ketelitian & Uji Soal',
    rarity: 'mythic',
    icon: 'Award',
    emoji: '🏆',
    targetValue: 100,
    unit: 'soal',
    xpReward: 1200,
    badgeStyle: {
      bg: 'bg-[#E2F0D9]',
      border: 'border-[#2E6930]',
      text: 'text-[#2E6930]',
      glow: 'shadow-lg shadow-[#2E6930]/30',
    },
  },
  {
    id: 'speedy_chem_cat',
    title: 'Refleks Kucing Cepat (Kilat 60 Detik)',
    description: 'Menyelesaikan 1 soal latihan mandiri dalam waktu kurang dari 60 detik dengan nilai minimal 8/10.',
    category: 'skill',
    categoryName: 'Ketelitian & Uji Soal',
    rarity: 'rare',
    icon: 'Zap',
    emoji: '🐱',
    targetValue: 1,
    unit: 'soal',
    xpReward: 100,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },

  // ==================== KATEGORI 3: EKSPLORASI ALAT LAB DIGITAL (11 BADGES) ====================
  {
    id: 'molar_mass_fan',
    title: 'Pencinta Massa Molar',
    description: 'Menggunakan kalkulator Mr sebanyak 10 kali untuk menghitung massa molar berbagai senyawa.',
    category: 'lab',
    categoryName: 'Alat Lab Digital',
    rarity: 'common',
    icon: 'FlaskConical',
    emoji: '🧪',
    targetValue: 10,
    unit: 'kali',
    xpReward: 50,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'scary_complex',
    title: 'Kompleks Menakutkan',
    description: 'Menghitung massa molar senyawa hidrat atau kompleks bertanda titik/kurung (misal: CuSO4.5H2O).',
    category: 'lab',
    categoryName: 'Alat Lab Digital',
    rarity: 'rare',
    icon: 'Binary',
    emoji: '🧊',
    targetValue: 1,
    unit: 'kali',
    xpReward: 75,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'mendeleev_explorer',
    title: 'Penjelajah Mendeleev',
    description: 'Mengklik dan menginspeksi rincian minimal 20 unsur berbeda pada Tabel Periodik interaktif.',
    category: 'lab',
    categoryName: 'Alat Lab Digital',
    rarity: 'common',
    icon: 'Compass',
    emoji: '🗺️',
    targetValue: 20,
    unit: 'unsur',
    xpReward: 60,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'rare_element_actinide',
    title: 'Spesialis Unsur Langka',
    description: 'Menginspeksi unsur radioaktif golongan Lantanida atau Aktinida pada Tabel Periodik.',
    category: 'lab',
    categoryName: 'Alat Lab Digital',
    rarity: 'rare',
    icon: 'Radioactive',
    emoji: '☢️',
    targetValue: 1,
    unit: 'kali',
    xpReward: 75,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'quick_formula_collector',
    title: 'Kolektor Rumus Cepat',
    description: 'Menyisipkan template formula dari pop-up Rumus Cepat Kimia ke lembar kerja sebanyak 5 kali.',
    category: 'lab',
    categoryName: 'Alat Lab Digital',
    rarity: 'common',
    icon: 'BookOpen',
    emoji: '📋',
    targetValue: 5,
    unit: 'kali',
    xpReward: 50,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'physics_constant_master',
    title: 'Ahli Tetapan Fisika',
    description: 'Menyalin nilai tetapan resmi (seperti R, tetapan Faraday, atau bilangan Avogadro) dari drawer tabel.',
    category: 'lab',
    categoryName: 'Alat Lab Digital',
    rarity: 'common',
    icon: 'Cpu',
    emoji: '📐',
    targetValue: 1,
    unit: 'kali',
    xpReward: 40,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'wet_whiteboard',
    title: 'Papan Tulis Basah',
    description: 'Membuka dan membuat catatan reaksi di modul Whiteboard selama minimal 5 menit.',
    category: 'lab',
    categoryName: 'Alat Lab Digital',
    rarity: 'rare',
    icon: 'PenTool',
    emoji: '🎨',
    targetValue: 5,
    unit: 'menit',
    xpReward: 80,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'periodic_century',
    title: 'Ensiklopedia Tabel Periodik (50 Unsur)',
    description: 'Menginspeksi detail informasi 50 unsur berbeda pada tabel periodik interaktif.',
    category: 'lab',
    categoryName: 'Alat Lab Digital',
    rarity: 'rare',
    icon: 'Grid',
    emoji: '🧪',
    targetValue: 50,
    unit: 'unsur',
    xpReward: 150,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'noble_gas_collector',
    title: 'Koleksi Gas Mulia (Oktet Sempurna)',
    description: 'Menginspeksi seluruh 6 unsur gas mulia (He, Ne, Ar, Kr, Xe, Rn) di tabel periodik.',
    category: 'lab',
    categoryName: 'Alat Lab Digital',
    rarity: 'rare',
    icon: 'Shield',
    emoji: '🎈',
    targetValue: 6,
    unit: 'unsur',
    xpReward: 100,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'scaffold_architect',
    title: 'Arsitek 4 Langkah OSN',
    description: 'Membuka pop-up Panduan Perancah 4 Langkah dan menyisipkan scaffold template ke lembar kerja sebanyak 3 kali.',
    category: 'lab',
    categoryName: 'Alat Lab Digital',
    rarity: 'common',
    icon: 'Layers',
    emoji: '🏗️',
    targetValue: 3,
    unit: 'kali',
    xpReward: 60,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'heavy_molar_titan',
    title: 'Titan Massa Raksasa (Mr > 500)',
    description: 'Menghitung massa molar senyawa raksasa dengan Mr di atas 500 g/mol di kalkulator Mr (misal klorofil atau polimer).',
    category: 'lab',
    categoryName: 'Alat Lab Digital',
    rarity: 'rare',
    icon: 'Scale',
    emoji: '⚖️',
    targetValue: 1,
    unit: 'kali',
    xpReward: 90,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },

  // ==================== KATEGORI 4: KEMAHIRAN KATEX & NOTASI ILMIAH (10 BADGES) ====================
  {
    id: 'katex_scribe',
    title: 'Juru Tulis Formula',
    description: 'Menggunakan sintaks KaTeX \\ce{...} untuk pertama kali pada lembar kerja pengerjaan soal.',
    category: 'katex',
    categoryName: 'Notasi Ilmiah & KaTeX',
    rarity: 'common',
    icon: 'Sparkles',
    emoji: '✍️',
    targetValue: 1,
    unit: 'kali',
    xpReward: 30,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'le_chatelier_digital',
    title: 'Asas Le Chatelier Digital',
    description: 'Menuliskan reaksi kesetimbangan bolak-balik menggunakan panah ganda (\\rightleftharpoons atau <=>) di lembar kerja.',
    category: 'katex',
    categoryName: 'Notasi Ilmiah & KaTeX',
    rarity: 'common',
    icon: 'Split',
    emoji: '🔁',
    targetValue: 1,
    unit: 'kali',
    xpReward: 40,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'stacked_fractions',
    title: 'Fraksi Bertumpuk',
    description: 'Menuliskan formula pecahan matematis menggunakan \\frac{...}{...} dalam langkah penalaran.',
    category: 'katex',
    categoryName: 'Notasi Ilmiah & KaTeX',
    rarity: 'common',
    icon: 'Divide',
    emoji: '➗',
    targetValue: 1,
    unit: 'kali',
    xpReward: 40,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'standard_thermo',
    title: 'Kondisi Termo Standar',
    description: 'Menggunakan simbol derajat standar (ΔH°, ΔG°, atau S°) dalam langkah penyelesaian soal.',
    category: 'katex',
    categoryName: 'Notasi Ilmiah & KaTeX',
    rarity: 'rare',
    icon: 'Thermometer',
    emoji: '🌡️',
    targetValue: 1,
    unit: 'kali',
    xpReward: 60,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'flawless_calligraphy',
    title: 'Kaligrafi Kimia Mulus',
    description: 'Menuliskan uraian KaTeX panjang (>150 karakter) yang ter-render 100% sempurna tanpa error sintaks.',
    category: 'katex',
    categoryName: 'Notasi Ilmiah & KaTeX',
    rarity: 'epic',
    icon: 'Scroll',
    emoji: '📜',
    targetValue: 1,
    unit: 'kali',
    xpReward: 150,
    badgeStyle: {
      bg: 'bg-[#FFF2CC]',
      border: 'border-[#D4A359]',
      text: 'text-[#806000]',
      glow: 'shadow-md shadow-[#D4A359]/20',
    },
  },
  {
    id: 'ionic_charge_radical',
    title: 'Ionik & Radikal',
    description: 'Menuliskan muatan kation/anion lengkap dengan eksponen kuadratik (seperti SO4^{2-} atau Al^{3+}).',
    category: 'katex',
    categoryName: 'Notasi Ilmiah & KaTeX',
    rarity: 'common',
    icon: 'Atom',
    emoji: '➕',
    targetValue: 1,
    unit: 'kali',
    xpReward: 40,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'gas_liquid_phase_master',
    title: 'Pakar Fasa Zat (s, l, g, aq)',
    description: 'Menuliskan keempat fasa reaksi kimia (solid, liquid, gas, aqueous) lengkap dalam jawaban lembar kerja.',
    category: 'katex',
    categoryName: 'Notasi Ilmiah & KaTeX',
    rarity: 'common',
    icon: 'Waves',
    emoji: '💧',
    targetValue: 1,
    unit: 'kali',
    xpReward: 50,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'reaction_arrow_trio',
    title: 'Ahli Panah Reaksi (Gas & Endapan)',
    description: 'Menggunakan simbol panah gas menguap (\\uparrow), panah endapan (\\downarrow), atau panah reaksi di jawaban.',
    category: 'katex',
    categoryName: 'Notasi Ilmiah & KaTeX',
    rarity: 'common',
    icon: 'ArrowUpRight',
    emoji: '↗️',
    targetValue: 1,
    unit: 'kali',
    xpReward: 50,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'equilibrium_constant_expression',
    title: 'Ekspresi Tetapan Kesetimbangan (Kc / Ksp)',
    description: 'Menuliskan notasi hukum aksi massa K_c atau K_{sp} dalam format matematis KaTeX.',
    category: 'katex',
    categoryName: 'Notasi Ilmiah & KaTeX',
    rarity: 'rare',
    icon: 'Sigma',
    emoji: '⚖️',
    targetValue: 1,
    unit: 'kali',
    xpReward: 70,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'scientific_exponential_notation',
    title: 'Notasi Eksponen Ilmiah (× 10ⁿ)',
    description: 'Menuliskan perhitungan notasi ilmiah eksponen (\\times 10^{n} atau 10^-n) di lembar jawaban.',
    category: 'katex',
    categoryName: 'Notasi Ilmiah & KaTeX',
    rarity: 'common',
    icon: 'Superscript',
    emoji: '🔢',
    targetValue: 1,
    unit: 'kali',
    xpReward: 50,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },

  // ==================== KATEGORI 5: AKSI UNIK, HUMOR, & MISI RAHASIA (17 BADGES) ====================
  {
    id: 'zen_master',
    title: 'Zen Master (Anti Distraksi)',
    description: 'Mengerjakan lembar kerja dalam mode layar penuh (Zen Mode) selama minimal 10 menit tanpa keluar.',
    category: 'quirk',
    categoryName: 'Misi Unik & Rahasia',
    rarity: 'common',
    icon: 'Smile',
    emoji: '🧘',
    targetValue: 10,
    unit: 'menit',
    xpReward: 50,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'data_saver',
    title: 'Penyelamat Data',
    description: 'Menekan tombol Simpan Progress manual sebanyak 15 kali untuk memastikan jawaban aman tersimpan.',
    category: 'quirk',
    categoryName: 'Misi Unik & Rahasia',
    rarity: 'common',
    icon: 'Save',
    emoji: '💾',
    targetValue: 15,
    unit: 'kali',
    xpReward: 40,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'not_just_water',
    title: 'Bukan Cuma Air!',
    description: 'Iseng mengecek massa molar "H2O" di kalkulator Mr (padahal semua orang sudah tahu Mr = 18!).',
    category: 'quirk',
    categoryName: 'Misi Unik & Rahasia',
    rarity: 'secret',
    isSecret: true,
    secretHint: 'Coba hitung massa molar molekul kehidupan paling umum di kalkulator Mr...',
    icon: 'Droplets',
    emoji: '💧',
    targetValue: 1,
    unit: 'kali',
    xpReward: 50,
    badgeStyle: {
      bg: 'bg-gradient-to-r from-purple-100 to-amber-100',
      border: 'border-purple-300',
      text: 'text-purple-900',
      glow: 'shadow-md shadow-purple-500/20',
    },
  },
  {
    id: 'sugar_seeker',
    title: 'Manisnya Kimia',
    description: 'Menghitung massa molar molekul gula seperti glukosa (C6H12O6) atau sukrosa pada kalkulator Mr.',
    category: 'quirk',
    categoryName: 'Misi Unik & Rahasia',
    rarity: 'secret',
    isSecret: true,
    secretHint: 'Hitung senyawa pembawa energi manis yang sering dipelajari di fotosintesis...',
    icon: 'Cookie',
    emoji: '🍫',
    targetValue: 1,
    unit: 'kali',
    xpReward: 60,
    badgeStyle: {
      bg: 'bg-gradient-to-r from-purple-100 to-amber-100',
      border: 'border-purple-300',
      text: 'text-purple-900',
      glow: 'shadow-md shadow-purple-500/20',
    },
  },
  {
    id: 'bookworm_marathon',
    title: 'Kutu Buku Maraton',
    description: 'Menyelesaikan dan menandai 3 modul bacaan teori kimia berbeda dalam rentang waktu 1 hari.',
    category: 'quirk',
    categoryName: 'Misi Unik & Rahasia',
    rarity: 'rare',
    icon: 'BookOpen',
    emoji: '📖',
    targetValue: 3,
    unit: 'modul',
    xpReward: 120,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'optical_microscope',
    title: 'Mikroskopis Optik',
    description: 'Membuka dan memperbesar gambar kurva/diagram soal dengan penampil resolusi tinggi.',
    category: 'quirk',
    categoryName: 'Misi Unik & Rahasia',
    rarity: 'common',
    icon: 'Glasses',
    emoji: '🔍',
    targetValue: 1,
    unit: 'kali',
    xpReward: 40,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'true_alchemist',
    title: 'Alkemis Sejati (Penjelajah Penuh)',
    description: 'Berhasil membuka minimal 30 dari seluruh koleksi achievement lencana yang ada.',
    category: 'quirk',
    categoryName: 'Misi Unik & Rahasia',
    rarity: 'mythic',
    icon: 'Diamond',
    emoji: '🌟',
    targetValue: 30,
    unit: 'lencana',
    xpReward: 1500,
    badgeStyle: {
      bg: 'bg-[#E2F0D9]',
      border: 'border-[#2E6930]',
      text: 'text-[#2E6930]',
      glow: 'shadow-lg shadow-[#2E6930]/30',
    },
  },
  {
    id: 'caffeine_boost',
    title: 'Doping Kafein Kucing Lab',
    description: 'Menghitung massa molar rumus molekul kafein "C8H10N4O2" di kalkulator Mr saat begadang!',
    category: 'quirk',
    categoryName: 'Misi Unik & Rahasia',
    rarity: 'secret',
    isSecret: true,
    secretHint: 'Molekul penahan kantuk yang ada di kopi dan teh favorit peneliti...',
    icon: 'Coffee',
    emoji: '☕',
    targetValue: 1,
    unit: 'kali',
    xpReward: 80,
    badgeStyle: {
      bg: 'bg-gradient-to-r from-purple-100 to-amber-100',
      border: 'border-purple-300',
      text: 'text-purple-900',
      glow: 'shadow-md shadow-purple-500/20',
    },
  },
  {
    id: 'cat_element_felix',
    title: 'Unsur Felinium (Kucing Besi)',
    description: 'Menghitung massa molar senyawa yang mengandung unsur Besi (Fe) atau menginspeksi Besi (Ferrum) di tabel periodik.',
    category: 'quirk',
    categoryName: 'Misi Unik & Rahasia',
    rarity: 'secret',
    isSecret: true,
    secretHint: 'Unsur dengan lambang Fe... mirip nama kucing Feline!',
    icon: 'Heart',
    emoji: '🐾',
    targetValue: 1,
    unit: 'kali',
    xpReward: 70,
    badgeStyle: {
      bg: 'bg-gradient-to-r from-purple-100 to-amber-100',
      border: 'border-purple-300',
      text: 'text-purple-900',
      glow: 'shadow-md shadow-purple-500/20',
    },
  },
  {
    id: 'radioactive_cat',
    title: 'Kucing Schrödinger Radioaktif',
    description: 'Menginspeksi unsur Uranium (U) atau Plutonium (Pu) pada tabel periodik.',
    category: 'quirk',
    categoryName: 'Misi Unik & Rahasia',
    rarity: 'secret',
    isSecret: true,
    secretHint: 'Unsur nomor 92 yang paling terkenal dalam reaksi fisi nuklir...',
    icon: 'Radioactive',
    emoji: '📦',
    targetValue: 1,
    unit: 'kali',
    xpReward: 90,
    badgeStyle: {
      bg: 'bg-gradient-to-r from-purple-100 to-amber-100',
      border: 'border-purple-300',
      text: 'text-purple-900',
      glow: 'shadow-md shadow-purple-500/20',
    },
  },
  {
    id: 'salt_of_the_earth',
    title: 'Garam Dapur Penambah Rasa',
    description: 'Menghitung Mr garam dapur "NaCl" di kalkulator Mr.',
    category: 'quirk',
    categoryName: 'Misi Unik & Rahasia',
    rarity: 'secret',
    isSecret: true,
    secretHint: 'Bumbu dapur ionik paling mendasar di meja makan...',
    icon: 'Sparkle',
    emoji: '🧂',
    targetValue: 1,
    unit: 'kali',
    xpReward: 50,
    badgeStyle: {
      bg: 'bg-gradient-to-r from-purple-100 to-amber-100',
      border: 'border-purple-300',
      text: 'text-purple-900',
      glow: 'shadow-md shadow-purple-500/20',
    },
  },
  {
    id: 'vinegar_reaction',
    title: 'Aroma Asam Cuka',
    description: 'Menghitung Mr asam asetat / cuka dapur "CH3COOH" di kalkulator Mr.',
    category: 'quirk',
    categoryName: 'Misi Unik & Rahasia',
    rarity: 'secret',
    isSecret: true,
    secretHint: 'Asam karboksilat beraroma khas yang sering dipakai di bakso...',
    icon: 'FlaskConical',
    emoji: '🥣',
    targetValue: 1,
    unit: 'kali',
    xpReward: 50,
    badgeStyle: {
      bg: 'bg-gradient-to-r from-purple-100 to-amber-100',
      border: 'border-purple-300',
      text: 'text-purple-900',
      glow: 'shadow-md shadow-purple-500/20',
    },
  },
  {
    id: 'schrodinger_whisperer',
    title: 'Bisikan Kucing Kuantum',
    description: 'Membaca modul pengantar Mekanika Kuantum & Konfigurasi Elektron di database materi.',
    category: 'quirk',
    categoryName: 'Misi Unik & Rahasia',
    rarity: 'rare',
    icon: 'Compass',
    emoji: '🐱',
    targetValue: 1,
    unit: 'kali',
    xpReward: 80,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'tab_surfer',
    title: 'Peselancar Tab Cepat',
    description: 'Berpindah-pindah antar nomor soal latihan sebanyak 20 kali dalam satu sesi pengerjaan.',
    category: 'quirk',
    categoryName: 'Misi Unik & Rahasia',
    rarity: 'common',
    icon: 'Navigation',
    emoji: '🏄',
    targetValue: 20,
    unit: 'pindah',
    xpReward: 40,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'canvas_zoom_curious',
    title: 'Mata Elang Pengatur Skala',
    description: 'Mencoba mengatur skala kanvas lembar kerja (Scale Toggle 75%, 100%, atau 125%) sebanyak 3 kali.',
    category: 'quirk',
    categoryName: 'Misi Unik & Rahasia',
    rarity: 'common',
    icon: 'ZoomIn',
    emoji: '🔍',
    targetValue: 3,
    unit: 'kali',
    xpReward: 40,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'chemistry_quote_reader',
    title: 'Pencari Hikmah Sains',
    description: 'Membuka dan membaca informasi tip atau glosarium sains pada beranda dashboard siswa.',
    category: 'quirk',
    categoryName: 'Misi Unik & Rahasia',
    rarity: 'common',
    icon: 'Bookmark',
    emoji: '💡',
    targetValue: 1,
    unit: 'kali',
    xpReward: 30,
    badgeStyle: {
      bg: 'bg-[#F0F8FF]',
      border: 'border-[#B0C4DE]',
      text: 'text-[#2D3748]',
      glow: '',
    },
  },
  {
    id: 'grand_master_chemist',
    title: 'Legenda Meow Alkemis (50 Lencana)',
    description: 'Membuka 50 lencana achievement! Anda resmi diangkat menjadi Mahaguru Kucing Kimia OSN sejati.',
    category: 'quirk',
    categoryName: 'Misi Unik & Rahasia',
    rarity: 'secret',
    isSecret: true,
    secretHint: 'Koleksi hampir seluruh lencana penghargaan di ruang prestasi...',
    icon: 'Crown',
    emoji: '👑',
    targetValue: 50,
    unit: 'lencana',
    xpReward: 2500,
    badgeStyle: {
      bg: 'bg-gradient-to-r from-purple-100 to-amber-100',
      border: 'border-purple-300',
      text: 'text-purple-900',
      glow: 'shadow-lg shadow-purple-500/30 ring-2 ring-purple-400',
    },
  },
];

/**
 * Mencari definisi achievement berdasarkan id
 */
export function getAchievementDefinition(id: string): AchievementDefinition | undefined {
  return ACHIEVEMENTS.find((a) => a.id === id);
}
