import type { ThemePalette } from '../types/theme';

export const THEME_PRESETS: ThemePalette[] = [
  {
    id: 'serene-minimalist',
    name: 'Serene Minimalist',
    subtitle: 'Palet Bawaan (Default)',
    description: 'Harmoni tenang bernuansa akademis dengan kombinasi Alice Blue, Ivory, Light Steel Blue, dan Slate Gray.',
    tags: ['Default', 'Calm', 'Academic', 'Slate Gray'],
    swatches: [
      { name: 'Ivory', hex: '#FFFFF0', rgb: 'rgb(255, 255, 240)' },
      { name: 'Alice Blue', hex: '#F0F8FF', rgb: 'rgb(240, 248, 255)' },
      { name: 'Light Steel Blue', hex: '#B0C4DE', rgb: 'rgb(176, 196, 222)' },
      { name: 'Light Gray', hex: '#D3D3D3', rgb: 'rgb(211, 211, 211)' },
      { name: 'Slate Gray', hex: '#708090', rgb: 'rgb(112, 128, 144)' },
    ],
    tokens: {
      canvas: '#F0F8FF',
      surface: '#FFFFF0',
      surfaceSecondary: '#F8FAF8',
      border: '#D3D3D3',
      primary: '#708090',
      primaryHover: '#5C6D7D',
      primaryText: '#FFFFF0',
      accent: '#B0C4DE',
      accentText: '#0F172A',
      text: '#2D3748',
      textMuted: '#708090',
      hero: {
        from: '#596A7A',
        via: '#708090',
        to: '#5C6D7D',
        text: '#FFFFF0',
        desc: '#F0F8FF',
        accent: '#B0C4DE',
      },
    },
  },
  {
    id: 'pastel-vintage',
    name: 'Pastel Vintage & Lavender',
    subtitle: 'Koleksi Gambar 1',
    description: 'Nuansa lembut perpaduan Soft Yellow Cream, Pastel Blue, Dusty Lavender, dan Warm Mauve Brown yang menenangkan.',
    tags: ['Pastel', 'Vintage', 'Soft', 'Lavender'],
    swatches: [
      { name: 'Cream Vanilla', hex: '#FDF4D2', rgb: 'rgb(253, 244, 210)' },
      { name: 'Pastel Sky', hex: '#B0CDE6', rgb: 'rgb(176, 205, 230)' },
      { name: 'Dusty Lavender', hex: '#A290B7', rgb: 'rgb(162, 144, 183)' },
      { name: 'Mauve Brown', hex: '#946D6D', rgb: 'rgb(148, 109, 109)' },
    ],
    tokens: {
      canvas: '#FBF9F4',
      surface: '#FDF4D2',
      surfaceSecondary: '#FAF0E4',
      border: '#DDD0C0',
      primary: '#946D6D',
      primaryHover: '#7F5959',
      primaryText: '#FDF4D2',
      accent: '#B0CDE6',
      accentText: '#1E293B',
      text: '#3A2E2E',
      textMuted: '#7A6B6B',
      hero: {
        from: '#825E5E',
        via: '#946D6D',
        to: '#7A6488',
        text: '#FDF4D2',
        desc: '#FCEFD7',
        accent: '#B0CDE6',
      },
    },
  },
  {
    id: 'deep-midnight-ocean',
    name: 'Deep Midnight & Royal Blue',
    subtitle: 'Koleksi Gambar 2',
    description: 'Palet modern berenergi tinggi dengan kontras tajam Midnight Navy, Royal Electric Blue, Cornflower Blue, dan Ice Blue.',
    tags: ['Modern', 'High-Contrast', 'Royal Blue', 'Tech'],
    swatches: [
      { name: 'Midnight Navy', hex: '#091540', rgb: 'rgb(9, 21, 64)' },
      { name: 'Royal Blue', hex: '#1B2CC1', rgb: 'rgb(27, 44, 193)' },
      { name: 'Cornflower Blue', hex: '#7692FF', rgb: 'rgb(118, 146, 255)' },
      { name: 'Ice Blue', hex: '#ABD2FA', rgb: 'rgb(171, 210, 250)' },
    ],
    tokens: {
      canvas: '#F0F5FA',
      surface: '#FFFFFF',
      surfaceSecondary: '#E8F1FC',
      border: '#C5D8F2',
      primary: '#1B2CC1',
      primaryHover: '#14229E',
      primaryText: '#FFFFFF',
      accent: '#7692FF',
      accentText: '#091540',
      text: '#091540',
      textMuted: '#43507B',
      hero: {
        from: '#091540',
        via: '#122378',
        to: '#1B2CC1',
        text: '#FFFFFF',
        desc: '#ABD2FA',
        accent: '#7692FF',
      },
    },
  },
  {
    id: 'terracotta-marine',
    name: 'Terracotta & Marine Blue',
    subtitle: 'Koleksi Gambar 3',
    description: 'Kombinasi klasik elegan Linen Cream, Terracotta Coral yang hangat, Deep Marine Blue yang tegas, dan Dark Espresso.',
    tags: ['Retro Modern', 'Warm & Cool', 'Terracotta', 'Marine Blue'],
    swatches: [
      { name: 'Almond Linen', hex: '#F5EBDD', rgb: 'rgb(245, 235, 221)' },
      { name: 'Terracotta Coral', hex: '#F2765E', rgb: 'rgb(242, 118, 94)' },
      { name: 'Marine Blue', hex: '#315B8C', rgb: 'rgb(49, 91, 140)' },
      { name: 'Dark Espresso', hex: '#413333', rgb: 'rgb(65, 51, 51)' },
    ],
    tokens: {
      canvas: '#F8F4EE',
      surface: '#F5EBDD',
      surfaceSecondary: '#EFE3D3',
      border: '#D8CABB',
      primary: '#315B8C',
      primaryHover: '#234469',
      primaryText: '#FFFFFF',
      accent: '#F2765E',
      accentText: '#26486F',
      text: '#413333',
      textMuted: '#685959',
      hero: {
        from: '#26486F',
        via: '#315B8C',
        to: '#233852',
        text: '#F5EBDD',
        desc: '#EFE4D3',
        accent: '#F2765E',
      },
    },
  },
  {
    id: 'scandinavian-slate',
    name: 'Scandinavian Slate & Ink',
    subtitle: 'Koleksi Gambar 4',
    description: 'Estetika minimalis Nordik dengan latar Sand Cream, Slate Sky Blue, Classic Slate Blue, dan aksen tinta hitam legam.',
    tags: ['Nordic', 'Clean Slate', 'Denim', 'High Readability'],
    swatches: [
      { name: 'Pale Sand', hex: '#EFECE3', rgb: 'rgb(239, 236, 227)' },
      { name: 'Slate Sky', hex: '#8FABD4', rgb: 'rgb(143, 171, 212)' },
      { name: 'Classic Slate', hex: '#4A70A9', rgb: 'rgb(74, 112, 169)' },
      { name: 'Pitch Black', hex: '#000000', rgb: 'rgb(0, 0, 0)' },
    ],
    tokens: {
      canvas: '#F6F4EE',
      surface: '#EFECE3',
      surfaceSecondary: '#E8E3D7',
      border: '#D3CDC0',
      primary: '#4A70A9',
      primaryHover: '#385888',
      primaryText: '#FFFFFF',
      accent: '#8FABD4',
      accentText: '#1A2942',
      text: '#11151A',
      textMuted: '#515B66',
      hero: {
        from: '#2A4469',
        via: '#4A70A9',
        to: '#35537F',
        text: '#EFECE3',
        desc: '#DFE8F3',
        accent: '#8FABD4',
      },
    },
  },
  {
    id: 'nordic-dune',
    name: 'Nordic Dune & Glacier Blue',
    subtitle: 'Koleksi Gambar 5',
    description: 'Keseimbangan alami bernuansa pesisir utara: Dusty Cadet Blue, Glacier Blue, Warm Sand Bisque, dan Soft Taupe Khaki.',
    tags: ['Nature', 'Coastal', 'Cadet Blue', 'Subtle & Relaxing'],
    swatches: [
      { name: 'Cadet Blue', hex: '#81A6C6', rgb: 'rgb(129, 166, 198)' },
      { name: 'Glacier Blue', hex: '#AACDDC', rgb: 'rgb(170, 205, 220)' },
      { name: 'Bisque Sand', hex: '#F3E3D0', rgb: 'rgb(243, 227, 208)' },
      { name: 'Taupe Khaki', hex: '#D2C4B4', rgb: 'rgb(210, 196, 180)' },
    ],
    tokens: {
      canvas: '#F5F8FA',
      surface: '#FBF7F1',
      surfaceSecondary: '#F3E3D0',
      border: '#D2C4B4',
      primary: '#6086A7',
      primaryHover: '#4C6F8E',
      primaryText: '#FFFFFF',
      accent: '#AACDDC',
      accentText: '#0F172A',
      text: '#2C3A46',
      textMuted: '#637482',
      hero: {
        from: '#4F7290',
        via: '#6086A7',
        to: '#537694',
        text: '#FFFFFF',
        desc: '#F3E3D0',
        accent: '#AACDDC',
      },
    },
  },
];
