import { OSN_MATERIALS } from '../src/data/materialsData.ts';
import { SMA_MATERIALS } from '../src/data/smaMaterialsData.ts';
import { IGCSE_MATERIALS } from '../src/data/igcseMaterialsData.ts';
import { parseAndRenderMixedText } from '../src/lib/katex-helpers.ts';

const allMaterials = [...OSN_MATERIALS, ...SMA_MATERIALS, ...IGCSE_MATERIALS];

let totalCalloutsFound = 0;
let totalCalloutsMatched = 0;

for (const mat of allMaterials) {
  for (const b of [...(mat.prerequisites || []), ...(mat.core_concepts || []), ...(mat.worked_examples || [])]) {
    const html = parseAndRenderMixedText(b.content);
    // count raw callouts generated by katex-helpers
    const rawMatches = html.match(/<div class="my-4 p-4(?:\.5)? [^"]*rounded-2xl border/gi) || [];
    totalCalloutsFound += rawMatches.length;

    // test regex match
    const transformedMatches = html.match(/<div class="my-4 p-4(?:\.5)? (?:rounded-2xl border|bg-emerald-50)[\s\S]*?<\/div>\s*<\/div>/gi) || [];
    totalCalloutsMatched += transformedMatches.length;
  }
}

console.log(`Total Callouts Found: ${totalCalloutsFound}`);
console.log(`Total Callouts Matched: ${totalCalloutsMatched}`);
